version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    external_links:
      - frontend

networks:
  default:
    external:
      name: slacky_default
