version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # environment:
    #   - DB_HOST=db
    #   - DB_PORT=3306
    #   - DB_USER=root
    #   - DB_PASSWORD=secret
    #   - DB_NAME=mydatabase
    ports:
      - "3000:3000"
    env_file:
      - .env
